config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/csrf_token", to: "csrf#index"

  get "/", to: "page#home"

  get "/user/new", to: "user#new", as: :signup_form
  post "/user/new", to: "user#create", as: :signup
  get "/login", to: "user#login", as: :login_form
  post "/login", to: "user#login_act", as: :login
  post "/api/login", to: "user#login_api", as: :login_api
  get "/logout", to: "user#destroy_session"

  get "/receipt", to: "receipt#list", as: :receipt_list
  post "/receipt", to: "receipt#create", as: :create_receipt
  get "/receipt/new", to: "receipt#create", as: :create_receipt_form
  get "/receipt/:id", to: "receipt#detail", as: :receipt_detail

  post "/receipt/:id/income", to: "income#create", as: :create_income
  get "/receipt/:id/income/new", to: "income#create", as: :create_income_form
  get "/income/:id/edit", to: "income#edit", as: :edit_income_form
  put "/income/:id/edit", to: "income#edit", as: :edit_income
  put "/income/:id/payment", to: "income#mark_as_paid", as: :mark_income_as_paid
  delete "/income/:id", to: "income#delete", as: :delete_income

  resources :income

  post "/receipt/:id/expense", to: "expense#create", as: :create_expense
  get "/receipt/:id/expense/new", to: "expense#create", as: :create_expense_form
  get "/expense/:id/edit", to: "expense#edit", as: :edit_expense_form
  put "/expense/:id/edit", to: "expense#edit", as: :edit_expense
  put "/expense/:id/payment", to: "expense#mark_as_paid", as: :mark_expense_as_paid
  delete "/expense/:id", to: "expense#delete", as: :delete_expense

  get "/receipt/:id/expense", to: "expense#detail", as: :expense_table
  get "/receipt/:id/income", to: "income#detail", as: :income_table
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/controllers/expense_controller.rb
class ExpenseController < ApplicationController
  def create
    name = params[:name]
    value = params[:value]
    installments_number = params[:installments_number]
    payment_date = params[:payment_date]

    @receipt_id = params[:id]

    @receipt_name = Receipt.find(@receipt_id).name

    does_receipt_exists = Receipt.exists?(@receipt_id)

    if not does_receipt_exists
      redirect_to "/receipt"
    end

    if name == nil && value == nil && installments_number == nil && payment_date == nil
      return
    end

    create_expense_page_url = "/receipt/#{@receipt_id}/expense/new"

    if name == ""
      redirect_to create_expense_page_url, alert: "O nome deve ser preenchido"
      return
    end

    if value == ""
      redirect_to create_expense_page_url, alert: "O valor deve ser preenchido"
      return
    end

    if payment_date == ""
      redirect_to create_expense_page_url, alert: "A data de pagamento deve ser definida"
      return
    end

    expense = Expense.new
    expense.id = SecureRandom.uuid
    expense.name = name
    expense.value = value
    expense.installments_number = installments_number
    expense.is_paid = false
    expense.payment_day = payment_date
    expense.receipt_id = @receipt_id

    expense.save

    redirect_to "/receipt/#{@receipt_id}/expense/new"
  end

  def edit
    @expense = Expense.find(params[:id])
    @receipt_id = @expense[:receipt_id]

    @receipt_name = Receipt.find(@expense[:receipt_id]).name

    name = params[:name]
    value = params[:value]
    installments_number = params[:installments_number]
    payment_day = params[:payment_date]

    if name == nil && value == nil && installments_number == nil && payment_day == nil
      return
    end
    if name != nil || name != ""
      @expense.name = name
    end

    if value != nil || value != 0
      @expense.value = value
    end

    if installments_number != nil || (installments_number != nil && installments_number >= 1)
      @expense.installments_number = installments_number
    end

    if payment_day != nil || (payment_day != nil && payment_day >= 1 && payment_day <= 31)
      @expense.payment_day = payment_day
    end

    @expense.save

    redirect_to "/receipt/#{@expense.receipt_id}"
  end

  def detail
    @receipt = Receipt.find(params[:id])

    @incomes = Income.where(receipt_id: params[:id])
    @expenses = Expense.where(receipt_id: params[:id])
  end

  def delete
    Expense.find(params[:id]).destroy
  end

  def mark_as_paid
    expense = Expense.find(params[:id])
    expense.is_paid = true

    expense.save
  end
end

app/helpers/expense_helper.rb
module ExpenseHelper
end

app/views/expense/create.html.erb
<div class="mx-auto max-w-screen-xl">
  <%= render "/components/breadcrumb/self" do %>
    <%= render "/components/breadcrumb/link", link: "/" do %>
      Início 
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/" do %>
      Receitas
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/#{@receipt_id}" do %>
      <%= @receipt_name %>
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/current" do %>
      Adicionar despesa
    <% end %>
  <% end %>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" data-controller="password-toggle" novalidate method="post" action=<%= "/receipt/#{@receipt_id}/expense" %> >
      <%= render "_shared/error" %>

      <div>
        <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nome</label>
        <div class="mt-2">
          <input id="name" name="name" type="text" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" autofocus>
        </div>
      </div>

      <div>
        <label for="value" class="block text-sm font-medium leading-6 text-gray-900">Valor</label>
        <div class="mt-2">
          <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-purple-600">
            <span class="flex select-none items-center pl-3 text-gray-500 border-0 text-sm">R$</span>
            <input id="value" name="value" type="number" class="bg-transparent block flex-1 border-0 py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="0.00">
          </div>
        </div>
      </div>

      <div>
        <label for="installments_number" class="block text-sm font-medium leading-6 text-gray-900">Parcelamento</label>
        <div class="mt-2">
          <input id="installments_number" name="installments_number" type="number" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" min="01" placeholder="1">
        </div>
      </div>

      <div>
        <label for="payment_date" class="block text-sm font-medium leading-6 text-gray-900">Data de pagamento</label>
        <div class="mt-2">
          <input id="payment_date" name="payment_date" type="number" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" min="01" max="31">
        </div>
      </div>

      <div>
        <button type="submit" class="w-full inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-purple-600 text-gray-50 hover:bg-purple-600/90 px-4 py-2">Criar</button>
      </div>
    </form>
  </div>
</div>

app/views/expense/detail.html.erb
<div class="mx-auto max-w-screen-xl">
  <%= render "/components/breadcrumb/self" do %>
    <%= render "/components/breadcrumb/link", link: "/" do %>
      Início 
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/" do %>
      Receitas
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/#{@receipt.id}" do %>
      <%= @receipt.name %>
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/current" do %>
      Despesas de <%= @receipt.name %>
    <% end %>
  <% end %>

  <div class="mt-10 rounded-md border border-gray-200">
    <div class="flex w-full items-center justify-between px-6 pb-3 pt-3">
      <div class="flex items-baseline space-x-2">
        <h4 class="font-bold text-gray-800">
          <%= @receipt.name %>
        </h4>
        <div class="inline-flex rounded-2xl bg-purple-100 px-2 py-1 text-xs font-bold text-purple-500">
          <% if @incomes.count == 1 %>
            <%= @incomes.count %> item
          <% end %>

          <% if @incomes.count != 1 %>
            <%= @incomes.count %> itens
          <% end %>
        </div>
      </div>
    
      <div class="flex space-x-2">
        <%= link_to "/receipt/#{@receipt.id}/income/new", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-green-600 text-gray-50 hover:bg-green-600/90 px-4 py-2" do %>
          <%= inline_svg_tag "plus.svg", class: 'mr-2 size-5' %>

          <span>Ganho</span>
        <% end %>

        <%= link_to "/receipt/#{@receipt.id}/expense/new", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-red-500 text-gray-50 hover:bg-red-500/90 px-4 py-2" do %>
          <%= inline_svg_tag "plus.svg", class: 'mr-2 size-5' %>

          <span>Despesa</span>
        <% end %>
      </div>
    </div>
    
    <div class="flex flex-col space-y-1 border-t border-b px-6 pb-3 pt-3">
      <div class="text-sm text-gray-700">
        <span class="font-semibold text-gray-600">
          Mês/Ano: 
        </span>
        <span>
          <%= l(@receipt.created_at, format: "%B/%Y") %>
        </span>
      </div>

      <div class="text-sm text-gray-700">
        <span class="font-semibold text-gray-600">
          Última atualização: 
        </span>
        <span>
          <%= l(@receipt.created_at, format: "%d/%m/%Y") %>
        </span>
      </div>

      <% if @expenses.count == 0 %>
        <div class="text-gray-700 text-sm flex items-center space-x-1">
          <%= inline_svg "expense.svg", class: 'fill-red-600 size-5 stroke-1' %>
          <span>
            Não há despesas cadastradas
          </span>
        </div>
      <% end %>

      <% if @incomes.count == 0 %>
        <div class="text-gray-700 text-sm flex items-center space-x-1">
          <%= inline_svg "income.svg", class: 'fill-green-600 size-5 stroke-1' %>
          <span>
            Não há ganhos cadastrados
          </span>
        </div>
      <% end %>
    </div>

    <div class="flex justify-between items-center px-6 py-3">
      <div class="flex items-center space-x-6">
        <a href=<%= "/receipt/#{@receipt.id}/income" %> class="relative z-10">
          <span class="font-medium text-sm text-gray-500">Ganhos</span>
          <span class="px-1 py-0.5 bg-gray-200/90 text-gray-600 rounded-sm text-xs"><%= @expenses.count %></span>
        </a>

        <a href=<%= "/receipt/#{@receipt.id}/expense" %> disabled=true class="relative z-10">
          <span class="font-medium text-sm text-gray-800">Despesas</span>
          <span class="px-1 py-0.5 bg-gray-200/90 text-gray-600 rounded-sm text-xs"><%= @expenses.count %></span>
          <span class="absolute inset-0 top-[26px] z-0 rounded-md bg-purple-500 h-0.5 w-full mx-auto"></span>
        </a>
      </div>

      <a role="button" href=<%= "/receipt/#{@receipt.id}" %> class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-white hover:bg-gray-50/90 hover:text-gray-600 h-9 px-3">Ver todas</a>
    </div>

    <div class="px-6 py-3 pt-3">
      <div class="flex flex-col space-y-4">
        <% if @expenses.count > 0 %>
          <%= render "partials/expense_table", collection: @expenses %>
        <% end %>
      </div>
    </div>
  </div>
<div>

app/views/expense/edit.html.erb
<div class="mx-auto max-w-screen-xl">
  <%= render "/components/breadcrumb/self" do %>
    <%= render "/components/breadcrumb/link", link: "/" do %>
      Início 
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/" do %>
      Receitas
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/#{@receipt_id}" do %>
      <%= @receipt_name %>
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/current" do %>
      Editar despesa
    <% end %>
  <% end %>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" data-controller="password-toggle" novalidate method="put" action=<%= "/expense/#{@expense.id}/edit" %> >
      <div>
        <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nome</label>
        <div class="mt-2">
          <input id="name" name="name" type="text" value=<%= @expense.name %> class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" autofocus>
        </div>
      </div>

      <div>
        <label for="value" class="block text-sm font-medium leading-6 text-gray-900">Valor</label>
        <div class="mt-2">
          <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-purple-600">
            <span class="flex select-none items-center pl-3 text-gray-500 border-0 text-sm">R$</span>
            <input id="value" name="value" type="number" value=<%= @expense.value %> class="bg-transparent block flex-1 border-0 py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="0.00">
          </div>
        </div>
      </div>

      <div>
        <label for="installments_number" class="block text-sm font-medium leading-6 text-gray-900">Parcelamento</label>
        <div class="mt-2">
          <input id="installments_number" name="installments_number" type="number" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" min="01" placeholder="1" value=<%= @expense.installments_number %> >
        </div>
      </div>

      <div>
        <label for="payment_date" class="block text-sm font-medium leading-6 text-gray-900">Data de pagamento</label>
        <div class="mt-2">
          <input id="payment_date" name="payment_date" type="number" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" min="01" max="31" value=<%= @expense.payment_day %>>
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-purple-700 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-purple-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-800">Atualizar</button>
      </div>
    </form>
  </div>
</div>

app/views/expense/list.html.erb
<div class="mx-auto max-w-screen-lg">
  <h2 class="mt-10 text-2xl font-bold tracking-tight leading-9 text-center text-gray-800">
    <div class="inline-block text-gray-700">Crie a primeira</div> 
    <div class="inline-block text-purple-600">lista de despesas</div>
  </h2>

  <% if not @exists_expense %>
    <form accept-charset="UTF-8" action="/expense" method="post">
      <div class="mx-auto max-w-xl sm:w-full">
        <button type="submit" class="flex justify-center items-center py-1.5 px-3 mx-auto mt-12 space-x-2 text-purple-700 rounded-md border border-purple-700 shadow-sm hover:text-white hover:bg-purple-700 fill-purple-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-800">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-5">
            <path fill-rule="evenodd" d="M12 3.75a.75.75 0 0 1 .75.75v6.75h6.75a.75.75 0 0 1 0 1.5h-6.75v6.75a.75.75 0 0 1-1.5 0v-6.75H4.5a.75.75 0 0 1 0-1.5h6.75V4.5a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd" />
          </svg>

          <div class="font-medium">Lista de despesa</div>
        </button>
      </div>
    </form>
  <% else %>
    <div class="mt-10">
      <% @expenses.each do |expense| %>
        <div class="justify-between flex items-center py-4 px-3 rounded-md border border-gray-100 bg-purple-200/40">
          <div>
            <h4 class="text-lg font-bold text-gray-600">
              <%= expense.name %>
            </h4>

            <small class="text-sm italic text-gray-600">
              <%= l(expense.updated_at, format: "%d de %B de %Y") %>
            </small>
          </div>

          <%= link_to "Acessar", expense_detail_path(expense), class: "rounded-md text-white text-sm px-3 py-1.5 bg-purple-700 flex hover:bg-purple-800 shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-800", role: "button" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>