config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/csrf_token", to: "csrf#index"

  get "/", to: "page#home"

  get "/user/new", to: "user#new", as: :signup_form
  post "/user/new", to: "user#create", as: :signup
  get "/login", to: "user#login", as: :login_form
  post "/login", to: "user#login_act", as: :login
  post "/api/login", to: "user#login_api", as: :login_api
  get "/logout", to: "user#destroy_session"

  get "/receipt", to: "receipt#list", as: :receipt_list
  post "/receipt", to: "receipt#create", as: :create_receipt
  get "/receipt/new", to: "receipt#create", as: :create_receipt_form
  get "/receipt/:id", to: "receipt#detail", as: :receipt_detail

  post "/receipt/:id/income", to: "income#create", as: :create_income
  get "/receipt/:id/income/new", to: "income#create", as: :create_income_form
  get "/income/:id/edit", to: "income#edit", as: :edit_income_form
  put "/income/:id/edit", to: "income#edit", as: :edit_income
  put "/income/:id/payment", to: "income#mark_as_paid", as: :mark_income_as_paid
  delete "/income/:id", to: "income#delete", as: :delete_income

  resources :income

  post "/receipt/:id/expense", to: "expense#create", as: :create_expense
  get "/receipt/:id/expense/new", to: "expense#create", as: :create_expense_form
  get "/expense/:id/edit", to: "expense#edit", as: :edit_expense_form
  put "/expense/:id/edit", to: "expense#edit", as: :edit_expense
  put "/expense/:id/payment", to: "expense#mark_as_paid", as: :mark_expense_as_paid
  delete "/expense/:id", to: "expense#delete", as: :delete_expense

  get "/receipt/:id/expense", to: "expense#detail", as: :expense_table
  get "/receipt/:id/income", to: "income#detail", as: :income_table
end

app/views/partials/_expense_table.html.erb
<%= render "components/table/self" do %>
  <%= render "components/table/table_header" do %>
    <th scope="col" class="px-6 py-3 w-4/12 font-medium">Nome</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Tipo</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Valor</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Parcelas</th>
    <th scope="col" class="px-6 py-3 w-1/12 font-medium">Pago</th>
    <th class="pr-6 py-1 pl-1 w-1/12"></th>
  <% end %>
  <%= render "components/table/table_body" do %>
    <% @expenses.each do |expense| %>
      <%= render "components/table/table_item" do %>
        <%= render "components/table/table_cell" do %>
          <%= expense.name %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          Despesa
        <% end %>

        <%= render "components/table/table_cell" do %>
          R$ <%= expense.value %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          <%= expense.installments_number %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          <%= expense.is_paid == true ? "Sim" : "Não" %>
        <% end %>

        <td class="pr-6 pl-1 py-1">
          <div class="flex justify-end relative" data-controller="dropdown">
            <button class="px-1 py-1 hover:bg-gray-100 transition rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none" data-action="click->dropdown#toggle">
              <%= inline_svg "ellipsis.svg", class: 'w-6 h-6 stroke-gray-800' %>
            </button>

            <div class="hidden absolute right-0 top-8 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1" data-dropdown-target="dropdown">
              <% if not expense.is_paid %>
                <div class="py-1" role="none">
                  <%= button_to "/expense/#{expense.id}/payment", class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", method: :put, role: "menuitem", tabindex: "-1" do %>
                    <%= inline_svg "check.svg", class: 'w-5 h-5 stroke-green-600' %>
                    <span>Marcar como pago</span>
                  <% end %>
                </div>
              <% end %>

              <div class="py-1" role="none">
                <%= button_to "/expense/#{expense.id}/edit", class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", method: :get, role: "menuitem", tabindex: "-1" do %>
                  <%= inline_svg "edit.svg", class: 'w-5 h-5 stroke-blue-600' %>
                  <span>Editar</span>
                <% end %>
              </div>

              <div class="py-1" role="none">
                <%= button_to "/expense/#{expense.id}", class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", method: :delete, role: "menuitem", tabindex: "-1" do %>
                  <%= inline_svg "trash.svg", class: 'w-5 h-5 stroke-red-600' %>
                  <span>Remover</span>
                <% end %>
              </div>
            </div>
          </div>
        </td>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/partials/_income_table.html.erb
<%= render "components/table/self" do %>
  <%= render "components/table/table_header" do %>
    <th scope="col" class="px-6 py-3 w-4/12 font-medium">Nome</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Tipo</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Valor</th>
    <th scope="col" class="px-6 py-3 w-2/12 font-medium">Mensal</th>
    <th scope="col" class="px-6 py-3 w-1/12 font-medium">Pago</th>
    <th class="pr-6 py-1 pl-1 w-1/12"></th>
  <% end %>
  <%= render "components/table/table_body" do %>
    <% collection.each do |income| %>
      <%= render "components/table/table_item" do %>
        <%= render "components/table/table_cell" do %>
          <%= income.name %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          Ganho
        <% end %>

        <%= render "components/table/table_cell" do %>
          R$ <%= income.value %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          <%= income.is_monthly_recurring == true ? "Sim" : "Não" %>
        <% end %>

        <%= render "components/table/table_cell" do %>
          <%= income.is_paid == true ? "Sim" : "Não" %>
        <% end %>

        <td class="pr-6 pl-1 py-1">
          <div class="flex justify-end relative" data-controller="dropdown">
            <button class="px-1 py-1 hover:bg-gray-100 transition rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none"  data-action="click->dropdown#toggle">
              <%= inline_svg "ellipsis.svg", class: 'w-6 h-6 stroke-gray-800' %>
            </button>

            <div class="hidden absolute z-50 right-0 top-8 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1" data-dropdown-target="dropdown">
              <% if not income.is_paid %>
                <div class="py-1" role="none">
                  <%= button_to "/income/#{income.id}/payment", class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", method: :put, role: "menuitem", tabindex: "-1" do %>
                    <%= inline_svg "check.svg", class: 'w-5 h-5 stroke-green-600' %>
                    <span>Marcar como pago</span>
                  <% end %>
                </div>
              <% end %>
              
                <div class="py-1" role="none">
                  <%= button_to "/income/#{income.id}/edit", class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", method: :get, role: "menuitem", tabindex: "-1" do %>
                    <%= inline_svg "edit.svg", class: 'w-5 h-5 stroke-blue-600' %>
                    <span>Editar</span>
                  <% end %>
                </div>

                <div class="py-1" role="none">
                  <%= button_to income_path(income), method: :delete, class: "flex space-x-1 items-center text-left w-full text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", role: "menuitem", tabindex: "-1" do %>
                    <%= inline_svg "trash.svg", class: 'w-5 h-5 stroke-red-600' %>

                    <span>Remover</span>
                  <% end %>
                </div>
            </div>
          </div>
        </td>
      <% end %>
    <% end %>
  <% end %>
<% end %>