config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/csrf_token", to: "csrf#index"

  get "/", to: "page#home"

  get "/user/new", to: "user#new", as: :signup_form
  post "/user/new", to: "user#create", as: :signup
  get "/login", to: "user#login", as: :login_form
  post "/login", to: "user#login_act", as: :login
  post "/api/login", to: "user#login_api", as: :login_api
  get "/logout", to: "user#destroy_session"

  get "/receipt", to: "receipt#list", as: :receipt_list
  post "/receipt", to: "receipt#create", as: :create_receipt
  get "/receipt/new", to: "receipt#create", as: :create_receipt_form
  get "/receipt/:id", to: "receipt#detail", as: :receipt_detail

  post "/receipt/:id/income", to: "income#create", as: :create_income
  get "/receipt/:id/income/new", to: "income#create", as: :create_income_form
  get "/income/:id/edit", to: "income#edit", as: :edit_income_form
  put "/income/:id/edit", to: "income#edit", as: :edit_income
  put "/income/:id/payment", to: "income#mark_as_paid", as: :mark_income_as_paid
  delete "/income/:id", to: "income#delete", as: :delete_income

  resources :income

  post "/receipt/:id/expense", to: "expense#create", as: :create_expense
  get "/receipt/:id/expense/new", to: "expense#create", as: :create_expense_form
  get "/expense/:id/edit", to: "expense#edit", as: :edit_expense_form
  put "/expense/:id/edit", to: "expense#edit", as: :edit_expense
  put "/expense/:id/payment", to: "expense#mark_as_paid", as: :mark_expense_as_paid
  delete "/expense/:id", to: "expense#delete", as: :delete_expense

  get "/receipt/:id/expense", to: "expense#detail", as: :expense_table
  get "/receipt/:id/income", to: "income#detail", as: :income_table
end

app/models/receipt.rb
class Receipt < ApplicationRecord
end

app/controllers/receipt_controller.rb
class ReceiptController < ApplicationController
  def list
    @receipts = Receipt.all

    receipt_count = Receipt.count

    @exists_receipt = receipt_count > 0
  end

  def detail
    @receipt = Receipt.find(params[:id])

    @incomes = Income.where(receipt_id: params[:id])
    @expenses = Expense.where(receipt_id: params[:id])
  end

  def create
    if params[:name] == nil
      return
    end

    if params[:name] != nil && params[:name] == ""
      redirect_to "/receipt/new", alert: "O nome deve ser preenchido"
      return
    end

    receipt = Receipt.new
    receipt.id = SecureRandom.uuid
    receipt.name = params[:name]
    receipt.user_id = session[:current_user_id]

    receipt.save

    redirect_to "/receipt"
  end
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/views/receipt/create.html.erb
<div class="mx-auto max-w-screen-xl">
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" data-controller="password-toggle" novalidate method="post" action="/receipt">
      <%= render "_shared/error" %>

      <div>
        <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nome</label>
        <div class="mt-2">
          <input id="name" name="name" type="text" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6" autofocus>
        </div>
      </div>

      <div>
        <button type="submit" class="w-full inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-purple-600 text-gray-50 hover:bg-purple-600/90 px-4 py-2">Criar</button>
      </div>
    </form>
  </div>
</div>

app/views/receipt/detail.html.erb
<div class="mx-auto max-w-screen-xl">
  <%= render "/components/breadcrumb/self" do %>
    <%= render "/components/breadcrumb/link", link: "/" do %>
      Início 
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/link", link: "/receipt/" do %>
      Receitas
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/current" do %>
      <%= @receipt.name %>
    <% end %>
  <% end %>

  <div class="mt-10 rounded-md border border-gray-200">
    <div class="flex w-full items-center justify-between px-6 pb-3 pt-3">
      <div class="flex items-baseline space-x-2">
        <h4 class="font-bold text-gray-800">
          <%= @receipt.name %>
        </h4>
      </div>
    
      <div class="flex space-x-2">
        <%= link_to "/receipt/#{@receipt.id}/income/new", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-green-600 text-gray-50 hover:bg-green-600/90 px-4 py-2" do %>
          <%= inline_svg_tag "plus.svg", class: 'mr-2 size-5' %>

          <span>Ganho</span>
        <% end %>

        <%= link_to "/receipt/#{@receipt.id}/expense/new", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-red-500 text-gray-50 hover:bg-red-500/90 px-4 py-2" do %>
          <%= inline_svg_tag "plus.svg", class: 'mr-2 size-5' %>

          <span>Despesa</span>
        <% end %>
      </div>
    </div>
    
    <div class="flex flex-col space-y-1 border-t border-b px-6 pb-3 pt-3">
      <div class="text-sm text-gray-700">
        <span class="font-semibold text-gray-600">
          Mês/Ano: 
        </span>
        <span>
          <%= l(@receipt.created_at, format: "%B/%Y") %>
        </span>
      </div>

      <div class="text-sm text-gray-700">
        <span class="font-semibold text-gray-600">
          Última atualização: 
        </span>
        <span>
          <%= l(@receipt.created_at, format: "%d/%m/%Y") %>
        </span>
      </div>

      <% if @expenses.count == 0 %>
        <div class="text-gray-700 text-sm flex items-center space-x-1">
          <%= inline_svg "expense.svg", class: 'fill-red-600 size-5 stroke-1' %>
          <span>
            Não há despesas cadastradas
          </span>
        </div>
      <% end %>

      <% if @incomes.count == 0 %>
        <div class="text-gray-700 text-sm flex items-center space-x-1">
          <%= inline_svg "income.svg", class: 'fill-green-600 size-5 stroke-1' %>
          <span>
            Não há ganhos cadastrados
          </span>
        </div>
      <% end %>
    </div>

    <div class="px-6 pb-9 pt-3">
      <div class="flex flex-col space-y-3">
        <div class="flex justify-between items-center">
          <h3 class="text-gray-700 font-semibold text-sm">
            Ganhos
            <span class="px-1 py-0.5 bg-gray-200/90 text-gray-600 rounded-sm text-xs"><%= @incomes.count %></span>
          </h3>

          <a role="button" href=<%= "/receipt/#{@receipt.id}/income" %> class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-white hover:bg-gray-50/90 hover:text-gray-600 h-9 px-3">Expandir</a>
        </div>

        <% if @incomes.count > 0 %>
          <%= render "partials/income_table", collection: @incomes %>
        <% end %>
      </div>
    </div>

    <div class="px-6 py-3">
      <div class="flex flex-col space-y-4">
        <div class="flex justify-between items-center">
          <h3 class="text-gray-800 font-semibold text-sm">
            Despesas
            <span class="px-1 py-0.5 bg-gray-200/90 text-gray-600 rounded-sm text-xs"><%= @expenses.count %></span>
          </h3>

          <a role="button" href=<%= "/receipt/#{@receipt.id}/expense" %> class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-white hover:bg-gray-50/90 hover:text-gray-600 h-9 px-3">Expandir</a>

        </div>

        <% if @expenses.count > 0 %>
          <%= render "partials/expense_table", collection: @expenses %>
        <% end %>
      </div>
    </div>
  </div>
<div>

app/views/receipt/list.html.erb
<div class="mx-auto max-w-screen-xl">
  <%= render "/components/breadcrumb/self" do %>
    <%= render "/components/breadcrumb/link", link: "/" do %>
      Início 
    <% end %>

    <%= render "/components/breadcrumb/separator" %>

    <%= render "/components/breadcrumb/current" do %>
      Receitas
    <% end %>
  <% end %>

  <% if not @exists_receipt %>
    <div class="mt-10 flex flex-col">
      <h2 class="self-center text-2xl font-bold leading-9 tracking-tight">
        <div class="inline-block text-gray-700">Crie a primeira</div>
        <div class="inline-block text-purple-600">receita</div>
      </h2>

      <div class="flex justify-center">
        <div class="mt-4 flex items-center rounded bg-purple-50 p-4">
          <%= inline_svg_tag "receipt.svg", class: 'w-16 mr-4 fill-purple-600' %>
          <div class="w-[38.75rem] text-left text-gray-700">Uma receita é o resultado cumulativo de todas as despesas e rendas registradas dentro de um mês específico</div>
        </div>
      </div>
    </div>
  <% end %>

  <% if not @exists_receipt %>
    <form accept-charset="UTF-8" action="/receipt" method="post">
      <div class="mx-auto max-w-xl sm:w-full">
        <input type="text" name="name" value="Lista de despesa 1" hidden />
        <button type="submit" class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2  focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-purple-500 text-gray-50 hover:bg-purple-500/90 px-4 py-2">
          <%= inline_svg_tag "plus.svg", class: 'mr-2 h-6 w-6' %>

          <span>Receita</span>
        </button>
      </div>
    </form>
  <% else %>
    <div class="mt-10 border border-gray-200 rounded-md">
      <div class="w-full px-6 pb-3 pt-3 flex justify-between items-center">
        <div class="flex space-x-2 items-baseline">
          <h4 class="font-bold text-gray-800">Receitas</h4>
          <div class="py-1 px-2 rounded-2xl bg-purple-100 text-purple-500 font-bold inline-flex text-xs">
            <% if @receipts.count == 1 %>
              <%= @receipts.count %> item
            <% end %>

            <% if @receipts.count != 1 %>
              <%= @receipts.count %> itens
            <% end %>
          </div>
        </div>

        <%= link_to "/receipt/new", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2  focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-purple-500 text-gray-50 hover:bg-purple-500/90 px-4 py-2" do %>
          <%= inline_svg_tag "plus.svg", class: 'mr-2 size-5' %>

          <span>Receita</span>
        <% end %>
      </div>

      <table class="w-full text-left text-gray-500">
        <thead class="text-sm bg-gray-50 border-y border-y-gray-200">
          <tr>
            <th scope="col" class="px-6 py-3">Nome</th>
            <th scope="col" class="px-6 py-3">Mês</th>
            <th scope="col" class="px-6 py-3">Ano</th>
            <th scope="col" class="px-6 py-3">Ganhos</th>
            <th scope="col" class="px-6 py-3">Despesas</th>
          </tr>
        </thead>
        <tbody class="text-sm text-gray-800">
          <% @receipts.each do |receipt| %>
            <tr class="bg-transparent border-b last:border-0">
              <th class="px-6 py-4 whitespace-nowrap font-bold text-purple-500">
                <%= link_to receipt.name, receipt_detail_path(receipt), class: "underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none rounded-sm" %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <%= l(receipt.created_at, format: "%B") %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <%= l(receipt.created_at, format: "%Y") %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">R$ 2000</td>
              <td class="px-6 py-4 whitespace-nowrap">R$ 1500</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>